-- =====================================================================
-- Wedding Invitation Platform — schema.sql (MariaDB)
--
-- Spring Boot auto-runs this file against the `wedding` database on
-- startup (see application.yml: spring.sql.init.mode=always). It must
-- be idempotent-safe to re-run, so every statement uses IF NOT EXISTS
-- where MariaDB supports it.
--
-- STATEMENT SEPARATOR: this file uses a custom two-character separator (not ";") as the boundary
-- between statements — see application.yml: spring.sql.init.separator.
-- That's required because trigger/procedure bodies below contain their
-- own internal ";" characters (one per inner statement in the BEGIN...END
-- block), and Spring Boot's script runner executes this file directly
-- over JDBC — it has no idea what a MySQL-CLI "DELIMITER" command is
-- (that's a client-only directive, not real SQL), so DELIMITER must
-- never appear in this file. Using the custom separator as the one global
-- boundary for the *entire* file (not just the trigger sections) avoids
-- needing it at all.
--
-- Design notes carried over from the original PostgreSQL version of
-- this schema, adapted for MariaDB:
--   - UUID primary keys are generated by Hibernate in the app
--     (GenerationType.UUID), not by the database, so columns are plain
--     CHAR(36) with no DEFAULT expression needed.
--   - created_at/updated_at are set by Hibernate (@CreationTimestamp /
--     @UpdateTimestamp), so DEFAULT/ON UPDATE clauses here are only a
--     safety net, not the source of truth.
--   - The four enum-like columns (role, media_type, moderation_status,
--     status) are VARCHAR + CHECK rather than a dedicated ENUM type —
--     matches the AttributeConverter mapping in the Java entities and
--     is easier to alter later than MariaDB's ENUM column type.
--   - Postgres arrays aren't available; guests.group_members is stored
--     as comma-separated TEXT and converted in the Java entity layer.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Fix the database's own default collation before anything else runs.
-- Table columns get their collation explicitly (COLLATE=utf8mb4_unicode_ci
-- on every CREATE TABLE below), but stored procedure parameters without
-- an explicit COLLATE clause inherit the DATABASE's default collation at
-- the moment CREATE PROCEDURE runs — not the connection's
-- collation_connection setting (that's a separate mechanism; see
-- application.yml's sessionVariables comment). If the database itself
-- was ever created without this exact COLLATE clause — e.g. just
-- CREATE DATABASE wedding CHARACTER SET utf8mb4; — MariaDB silently
-- falls back to its own server default (often utf8mb4_general_ci),
-- causing "Illegal mix of collations" errors on any procedure that
-- compares a parameter against a table column. No database name is
-- given below — ALTER DATABASE with no name applies to whichever
-- database the current connection is already using, so this is safe
-- regardless of what DB_NAME is configured to.
-- ---------------------------------------------------------------------

ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- ADMINS
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS admins (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    username        VARCHAR(64) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20) NOT NULL DEFAULT 'admin',
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_by      CHAR(36) NULL,
    last_login_at   DATETIME NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT uk_admins_username UNIQUE (username),
    CONSTRAINT ck_admins_role CHECK (role IN ('super_admin', 'admin')),
    CONSTRAINT fk_admins_created_by FOREIGN KEY (created_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- SEATING TABLES  (8 physical dinner tables, shared across the wedding)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS seating_tables (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    table_number    INT NOT NULL,
    capacity        INT NOT NULL DEFAULT 12,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT uk_seating_tables_number UNIQUE (table_number),
    CONSTRAINT ck_seating_tables_capacity CHECK (capacity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- GUESTS
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS guests (
    id                  CHAR(36) NOT NULL PRIMARY KEY,
    admin_id            CHAR(36) NOT NULL,
    display_name        VARCHAR(255) NOT NULL,
    is_group            TINYINT(1) NOT NULL DEFAULT 0,
    party_size          INT NOT NULL DEFAULT 1,
    group_members       TEXT NULL,              -- comma-separated names; see StringListCsvConverter
    greeting_message    TEXT NULL,
    language            VARCHAR(10) NOT NULL DEFAULT 'en',
    landing_slug        VARCHAR(64) NOT NULL,     -- generated app-side (SecureRandom), see Guest#generateSlug
    page_generated_at   DATETIME NULL,
    first_viewed_at     DATETIME NULL,
    table_id            CHAR(36) NULL,
    is_deleted          TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at          DATETIME NULL,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT uk_guests_landing_slug UNIQUE (landing_slug),
    CONSTRAINT ck_guests_party_size CHECK (party_size > 0),
    CONSTRAINT ck_guests_group_size CHECK (is_group = 1 OR party_size = 1),
    CONSTRAINT fk_guests_admin FOREIGN KEY (admin_id) REFERENCES admins (id) ON DELETE RESTRICT,
    CONSTRAINT fk_guests_table FOREIGN KEY (table_id) REFERENCES seating_tables (id) ON DELETE SET NULL,

    INDEX idx_guests_admin_id (admin_id),
    INDEX idx_guests_table_id (table_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- GUEST MEDIA  (max 15 photos / 4 videos per guest, enforced by trigger)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS guest_media (
    id                  CHAR(36) NOT NULL PRIMARY KEY,
    guest_id            CHAR(36) NOT NULL,
    media_type          VARCHAR(10) NOT NULL,
    storage_key         VARCHAR(500) NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    mime_type           VARCHAR(100) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    width_px            INT NULL,
    height_px           INT NULL,
    duration_seconds    INT NULL,
    moderation_status   VARCHAR(10) NOT NULL DEFAULT 'approved',
    uploaded_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_guest_media_type CHECK (media_type IN ('photo', 'video')),
    CONSTRAINT ck_guest_media_moderation CHECK (moderation_status IN ('approved', 'pending', 'rejected')),
    CONSTRAINT ck_guest_media_size CHECK (size_bytes > 0),
    CONSTRAINT fk_guest_media_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,

    INDEX idx_guest_media_guest_type (guest_id, media_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- IMPORT BATCHES  (.txt guest-list uploads)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS import_batches (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    admin_id        CHAR(36) NOT NULL,
    filename        VARCHAR(255) NOT NULL,
    status          VARCHAR(15) NOT NULL DEFAULT 'pending',
    total_rows      INT NOT NULL DEFAULT 0,
    success_rows    INT NOT NULL DEFAULT 0,
    error_rows      INT NOT NULL DEFAULT 0,
    imported_at     DATETIME NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_import_batches_status CHECK (status IN ('pending', 'completed', 'failed')),
    CONSTRAINT fk_import_batches_admin FOREIGN KEY (admin_id) REFERENCES admins (id) ON DELETE CASCADE,

    INDEX idx_import_batches_admin_id (admin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

CREATE TABLE IF NOT EXISTS import_batch_rows (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    batch_id        CHAR(36) NOT NULL,
    `row_number`    INT NOT NULL,
    raw_line        TEXT NOT NULL,
    guest_id        CHAR(36) NULL,
    error_message   TEXT NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_import_batch_rows_batch FOREIGN KEY (batch_id) REFERENCES import_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_import_batch_rows_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE SET NULL,

    INDEX idx_import_batch_rows_batch_id (batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- =====================================================================
-- TRIGGERS / STORED PROCEDURES  (business rules enforced in the DB
-- as a safety net behind the application-layer checks)
-- =====================================================================

DROP TRIGGER IF EXISTS trg_guest_media_limit$$

CREATE TRIGGER trg_guest_media_limit
BEFORE INSERT ON guest_media
FOR EACH ROW
BEGIN
    DECLARE current_count INT;
    DECLARE max_allowed INT;

    SELECT COUNT(*) INTO current_count
    FROM guest_media
    WHERE guest_id = NEW.guest_id AND media_type = NEW.media_type;

    IF NEW.media_type = 'photo' THEN
        SET max_allowed = 15;
    ELSE
        SET max_allowed = 4;
    END IF;

    IF current_count >= max_allowed THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Guest already has the maximum allowed uploads for this media type';
    END IF;
END$$

-- Table-capacity check factored into a procedure so both the INSERT and
-- UPDATE triggers on guests can share it (MariaDB has no "BEFORE INSERT
-- OR UPDATE" combined trigger the way Postgres does).
DROP PROCEDURE IF EXISTS check_table_capacity$$

CREATE PROCEDURE check_table_capacity(
    IN p_table_id CHAR(36),
    IN p_guest_id CHAR(36),
    IN p_party_size INT
)
BEGIN
    DECLARE v_capacity INT;
    DECLARE v_seats_taken INT;

    IF p_table_id IS NOT NULL THEN
        SELECT capacity INTO v_capacity FROM seating_tables WHERE id = p_table_id;

        SELECT COALESCE(SUM(party_size), 0) INTO v_seats_taken
        FROM guests
        WHERE table_id = p_table_id
          AND is_deleted = 0
          AND id <> p_guest_id;

        IF v_seats_taken + p_party_size > v_capacity THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'This table does not have enough seats left for this guest';
        END IF;
    END IF;
END$$

DROP TRIGGER IF EXISTS trg_guests_table_capacity_insert$$
DROP TRIGGER IF EXISTS trg_guests_table_capacity_update$$

CREATE TRIGGER trg_guests_table_capacity_insert
BEFORE INSERT ON guests
FOR EACH ROW
BEGIN
    CALL check_table_capacity(NEW.table_id, NEW.id, NEW.party_size);
END$$

CREATE TRIGGER trg_guests_table_capacity_update
BEFORE UPDATE ON guests
FOR EACH ROW
BEGIN
    CALL check_table_capacity(NEW.table_id, NEW.id, NEW.party_size);
END$$

-- =====================================================================
-- VIEWS
-- =====================================================================

CREATE OR REPLACE VIEW v_table_occupancy AS
SELECT
    st.id                                          AS table_id,
    st.table_number,
    st.capacity,
    COALESCE(SUM(g.party_size), 0)                 AS seats_taken,
    st.capacity - COALESCE(SUM(g.party_size), 0)    AS seats_left,
    COUNT(g.id)                                     AS parties_seated
FROM seating_tables st
LEFT JOIN guests g ON g.table_id = st.id AND g.is_deleted = 0
GROUP BY st.id, st.table_number, st.capacity
ORDER BY st.table_number$$

CREATE OR REPLACE VIEW v_guest_media_allowance AS
SELECT
    g.id AS guest_id,
    g.display_name,
    SUM(CASE WHEN gm.media_type = 'photo' THEN 1 ELSE 0 END)      AS photos_used,
    15 - SUM(CASE WHEN gm.media_type = 'photo' THEN 1 ELSE 0 END) AS photos_remaining,
    SUM(CASE WHEN gm.media_type = 'video' THEN 1 ELSE 0 END)      AS videos_used,
    4 - SUM(CASE WHEN gm.media_type = 'video' THEN 1 ELSE 0 END)  AS videos_remaining
FROM guests g
LEFT JOIN guest_media gm ON gm.guest_id = g.id
WHERE g.is_deleted = 0
GROUP BY g.id, g.display_name$$

CREATE OR REPLACE VIEW v_table_seating_super_admin AS
SELECT
    st.table_number,
    st.capacity,
    occ.seats_left,
    g.id           AS guest_id,
    g.display_name,
    g.party_size,
    a.username     AS owning_admin
FROM seating_tables st
JOIN v_table_occupancy occ ON occ.table_id = st.id
LEFT JOIN guests g ON g.table_id = st.id AND g.is_deleted = 0
LEFT JOIN admins a ON a.id = g.admin_id
ORDER BY st.table_number, g.display_name$$

-- ---------------------------------------------------------------------
-- Seating chart scoped to one admin — MariaDB has no table-valued SQL
-- function like Postgres, so this is a stored procedure returning a
-- result set instead of a view: CALL get_seating_chart_for_admin('...').
-- Defined further down (after the side/label columns exist below), not
-- here — the procedure body needs v_table_occupancy's "label" column,
-- which the HALL LAYOUT section below adds.
-- ---------------------------------------------------------------------

-- =====================================================================
-- HALL LAYOUT — bride/groom/head sides for seating_tables, plus which
-- side each admin belongs to. Appended as ALTER statements (not folded
-- into the CREATE TABLE blocks above) so this stays safely re-runnable
-- against a database that already has the original tables — every
-- ALTER here uses IF [NOT] EXISTS, a MariaDB extension supported since
-- 10.1.4/10.0.2, so re-running this on a database that's already been
-- migrated is a clean no-op rather than an error.
-- =====================================================================

-- Which side an admin belongs to. NULL for super_admin (not tied to a
-- side); required for a regular admin — enforced in the application
-- layer at admin-creation time, not by a NOT NULL here, since super_admin
-- genuinely has no side.
ALTER TABLE admins
    ADD COLUMN IF NOT EXISTS side VARCHAR(10) NULL CHECK (side IN ('bride', 'groom'))$$

-- seating_tables gains a side. table_number becomes nullable (the head
-- table isn't numbered) and its uniqueness becomes per-side instead of
-- global (both a "1B" and a "1D" table can coexist).
ALTER TABLE seating_tables
    ADD COLUMN IF NOT EXISTS side VARCHAR(10) NOT NULL DEFAULT 'bride' CHECK (side IN ('bride', 'groom', 'head'))$$

ALTER TABLE seating_tables MODIFY COLUMN table_number INT NULL$$

ALTER TABLE seating_tables DROP INDEX IF EXISTS uk_seating_tables_number$$

ALTER TABLE seating_tables ADD UNIQUE INDEX IF NOT EXISTS uk_seating_tables_side_number (side, table_number)$$

-- The original 8 generic tables (from before this feature existed) have
-- no meaningful side and don't fit the new model — clear them out ONCE
-- so data.sql can seed a proper head/bride/groom layout instead.
--
-- This must NOT run on every restart — schema.sql re-runs on every boot,
-- and admins will be creating/deleting their own tables through the app
-- from now on, so an unconditional DELETE here would silently wipe their
-- work on every subsequent restart. Guarded by a small migrations-applied
-- table so the cleanup fires exactly once, ever.

CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_name  VARCHAR(100) NOT NULL PRIMARY KEY,
    applied_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

DROP PROCEDURE IF EXISTS apply_hall_layout_migration$$

CREATE PROCEDURE apply_hall_layout_migration()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE migration_name = 'hall_layout_v1') THEN
        DELETE FROM seating_tables;
        INSERT INTO schema_migrations (migration_name) VALUES ('hall_layout_v1');
    END IF;
END$$

CALL apply_hall_layout_migration()$$
DROP PROCEDURE IF EXISTS apply_hall_layout_migration$$

-- ---------------------------------------------------------------------
-- Views/procedures updated to carry side + a display label
-- ---------------------------------------------------------------------

CREATE OR REPLACE VIEW v_table_occupancy AS
SELECT
    st.id AS table_id,
    st.side,
    st.table_number,
    CASE
        WHEN st.side = 'head' THEN 'Head Table'
        WHEN st.side = 'bride' THEN CONCAT(st.table_number, 'D')
        WHEN st.side = 'groom' THEN CONCAT(st.table_number, 'B')
    END AS label,
    st.capacity,
    COALESCE(SUM(g.party_size), 0) AS seats_taken,
    st.capacity - COALESCE(SUM(g.party_size), 0) AS seats_left,
    COUNT(g.id) AS parties_seated
FROM seating_tables st
LEFT JOIN guests g ON g.table_id = st.id AND g.is_deleted = 0
GROUP BY st.id, st.side, st.table_number, st.capacity
ORDER BY st.side, st.table_number$$

DROP PROCEDURE IF EXISTS get_seating_chart_for_admin$$

CREATE PROCEDURE get_seating_chart_for_admin(IN p_admin_id CHAR(36))
BEGIN
    -- super_admin sees every guest by name, same as if every guest were
    -- its own — computed once here rather than repeating the subquery
    -- per row.
    DECLARE v_is_super_admin BOOLEAN DEFAULT FALSE;
    SELECT (role = 'super_admin') INTO v_is_super_admin FROM admins WHERE id = p_admin_id;

    SELECT
        st.id AS table_id,
        st.side,
        st.table_number,
        occ.label,
        st.capacity,
        occ.seats_left,
        g.id AS guest_id,
        CASE WHEN v_is_super_admin OR g.admin_id = p_admin_id
             THEN g.display_name
             ELSE CONCAT('Reserved (', g.party_size, ' seats)')
        END AS display_name,
        g.party_size,
        (v_is_super_admin OR g.admin_id = p_admin_id) AS is_own_guest
    FROM seating_tables st
    JOIN v_table_occupancy occ ON occ.table_id = st.id
    LEFT JOIN guests g ON g.table_id = st.id AND g.is_deleted = 0
    ORDER BY st.side, st.table_number, is_own_guest DESC, g.display_name;
END$$