-- =====================================================================
-- Wedding Invitation Platform — schema.sql (MariaDB)
--
-- Spring Boot auto-runs this file against the `wedding` database on
-- startup (see application.yml: spring.sql.init.mode=always). It must
-- be idempotent-safe to re-run, so every statement uses IF NOT EXISTS
-- where MariaDB supports it.
--
-- STATEMENT SEPARATOR: this file uses a custom two-character separator (not ";") as the boundary
-- between statements — see application.yml: spring.sql.init.separator.
-- That's required because trigger/procedure bodies below contain their
-- own internal ";" characters (one per inner statement in the BEGIN...END
-- block), and Spring Boot's script runner executes this file directly
-- over JDBC — it has no idea what a MySQL-CLI "DELIMITER" command is
-- (that's a client-only directive, not real SQL), so DELIMITER must
-- never appear in this file. Using the custom separator as the one global
-- boundary for the *entire* file (not just the trigger sections) avoids
-- needing it at all.
--
-- Design notes carried over from the original PostgreSQL version of
-- this schema, adapted for MariaDB:
--   - UUID primary keys are generated by Hibernate in the app
--     (GenerationType.UUID), not by the database, so columns are plain
--     CHAR(36) with no DEFAULT expression needed.
--   - created_at/updated_at are set by Hibernate (@CreationTimestamp /
--     @UpdateTimestamp), so DEFAULT/ON UPDATE clauses here are only a
--     safety net, not the source of truth.
--   - The four enum-like columns (role, media_type, moderation_status,
--     status) are VARCHAR + CHECK rather than a dedicated ENUM type —
--     matches the AttributeConverter mapping in the Java entities and
--     is easier to alter later than MariaDB's ENUM column type.
--   - Postgres arrays aren't available; guests.group_members is stored
--     as comma-separated TEXT and converted in the Java entity layer.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Fix the database's own default collation before anything else runs.
-- Table columns get their collation explicitly (COLLATE=utf8mb4_unicode_ci
-- on every CREATE TABLE below), but stored procedure parameters without
-- an explicit COLLATE clause inherit the DATABASE's default collation at
-- the moment CREATE PROCEDURE runs — not the connection's
-- collation_connection setting (that's a separate mechanism; see
-- application.yml's sessionVariables comment). If the database itself
-- was ever created without this exact COLLATE clause — e.g. just
-- CREATE DATABASE wedding CHARACTER SET utf8mb4; — MariaDB silently
-- falls back to its own server default (often utf8mb4_general_ci),
-- causing "Illegal mix of collations" errors on any procedure that
-- compares a parameter against a table column. No database name is
-- given below — ALTER DATABASE with no name applies to whichever
-- database the current connection is already using, so this is safe
-- regardless of what DB_NAME is configured to.
-- ---------------------------------------------------------------------

ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- ADMINS
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS admins (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    username        VARCHAR(64) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20) NOT NULL DEFAULT 'admin',
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_by      CHAR(36) NULL,
    last_login_at   DATETIME NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT uk_admins_username UNIQUE (username),
    CONSTRAINT ck_admins_role CHECK (role IN ('super_admin', 'admin', 'dj', 'banker')),
    CONSTRAINT fk_admins_created_by FOREIGN KEY (created_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- SEATING TABLES  (8 physical dinner tables, shared across the wedding)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS seating_tables (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    table_number    INT NOT NULL,
    capacity        INT NOT NULL DEFAULT 12,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT uk_seating_tables_number UNIQUE (table_number),
    CONSTRAINT ck_seating_tables_capacity CHECK (capacity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- GUESTS
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS guests (
    id                  CHAR(36) NOT NULL PRIMARY KEY,
    admin_id            CHAR(36) NOT NULL,
    display_name        VARCHAR(255) NOT NULL,
    is_group            TINYINT(1) NOT NULL DEFAULT 0,
    party_size          INT NOT NULL DEFAULT 1,
    group_members       TEXT NULL,              -- comma-separated names; see StringListCsvConverter
    greeting_message    TEXT NULL,
    language            VARCHAR(10) NOT NULL DEFAULT 'ru',
    landing_slug        VARCHAR(64) NOT NULL,     -- generated app-side (SecureRandom), see Guest#generateSlug
    page_generated_at   DATETIME NULL,
    first_viewed_at     DATETIME NULL,
    table_id            CHAR(36) NULL,
    is_deleted          TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at          DATETIME NULL,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT uk_guests_landing_slug UNIQUE (landing_slug),
    CONSTRAINT ck_guests_party_size CHECK (party_size > 0),
    CONSTRAINT ck_guests_group_size CHECK (is_group = 1 OR party_size = 1),
    CONSTRAINT fk_guests_admin FOREIGN KEY (admin_id) REFERENCES admins (id) ON DELETE RESTRICT,
    CONSTRAINT fk_guests_table FOREIGN KEY (table_id) REFERENCES seating_tables (id) ON DELETE SET NULL,

    INDEX idx_guests_admin_id (admin_id),
    INDEX idx_guests_table_id (table_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- GUEST MEDIA  (max 15 photos / 4 videos per guest, enforced by trigger)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS guest_media (
    id                  CHAR(36) NOT NULL PRIMARY KEY,
    guest_id            CHAR(36) NOT NULL,
    media_type          VARCHAR(10) NOT NULL,
    storage_key         VARCHAR(500) NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    mime_type           VARCHAR(100) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    width_px            INT NULL,
    height_px           INT NULL,
    duration_seconds    INT NULL,
    moderation_status   VARCHAR(10) NOT NULL DEFAULT 'approved',
    uploaded_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_guest_media_type CHECK (media_type IN ('photo', 'video')),
    CONSTRAINT ck_guest_media_moderation CHECK (moderation_status IN ('approved', 'pending', 'rejected')),
    CONSTRAINT ck_guest_media_size CHECK (size_bytes > 0),
    CONSTRAINT fk_guest_media_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,

    INDEX idx_guest_media_guest_type (guest_id, media_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- GALLERY IMAGES  (invitation page's "about us" section, super-admin managed)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS gallery_images (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    storage_key     VARCHAR(500) NOT NULL,
    mime_type       VARCHAR(100) NOT NULL,
    caption_ru      VARCHAR(255) NOT NULL DEFAULT '',
    caption_uz      VARCHAR(255) NOT NULL DEFAULT '',
    caption_en      VARCHAR(255) NOT NULL DEFAULT '',
    display_order   INT NOT NULL DEFAULT 0,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT uk_gallery_images_storage_key UNIQUE (storage_key),
    INDEX idx_gallery_images_order (display_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- ---------------------------------------------------------------------
-- IMPORT BATCHES  (.txt guest-list uploads)
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS import_batches (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    admin_id        CHAR(36) NOT NULL,
    filename        VARCHAR(255) NOT NULL,
    status          VARCHAR(15) NOT NULL DEFAULT 'pending',
    total_rows      INT NOT NULL DEFAULT 0,
    success_rows    INT NOT NULL DEFAULT 0,
    error_rows      INT NOT NULL DEFAULT 0,
    imported_at     DATETIME NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_import_batches_status CHECK (status IN ('pending', 'completed', 'failed')),
    CONSTRAINT fk_import_batches_admin FOREIGN KEY (admin_id) REFERENCES admins (id) ON DELETE CASCADE,

    INDEX idx_import_batches_admin_id (admin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

CREATE TABLE IF NOT EXISTS import_batch_rows (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    batch_id        CHAR(36) NOT NULL,
    `row_number`    INT NOT NULL,
    raw_line        TEXT NOT NULL,
    guest_id        CHAR(36) NULL,
    error_message   TEXT NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_import_batch_rows_batch FOREIGN KEY (batch_id) REFERENCES import_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_import_batch_rows_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE SET NULL,

    INDEX idx_import_batch_rows_batch_id (batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- =====================================================================
-- TRIGGERS / STORED PROCEDURES  (business rules enforced in the DB
-- as a safety net behind the application-layer checks)
-- =====================================================================

DROP TRIGGER IF EXISTS trg_guest_media_limit$$

CREATE TRIGGER trg_guest_media_limit
BEFORE INSERT ON guest_media
FOR EACH ROW
BEGIN
    DECLARE current_count INT;
    DECLARE max_allowed INT;

    SELECT COUNT(*) INTO current_count
    FROM guest_media
    WHERE guest_id = NEW.guest_id AND media_type = NEW.media_type;

    IF NEW.media_type = 'photo' THEN
        SET max_allowed = 15;
    ELSE
        SET max_allowed = 4;
    END IF;

    IF current_count >= max_allowed THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Guest already has the maximum allowed uploads for this media type';
    END IF;
END$$

-- Table-capacity check factored into a procedure so both the INSERT and
-- UPDATE triggers on guests can share it (MariaDB has no "BEFORE INSERT
-- OR UPDATE" combined trigger the way Postgres does).
DROP PROCEDURE IF EXISTS check_table_capacity$$

CREATE PROCEDURE check_table_capacity(
    IN p_table_id CHAR(36),
    IN p_guest_id CHAR(36),
    IN p_party_size INT
)
BEGIN
    DECLARE v_capacity INT;
    DECLARE v_seats_taken INT;

    IF p_table_id IS NOT NULL THEN
        SELECT capacity INTO v_capacity FROM seating_tables WHERE id = p_table_id;

        SELECT COALESCE(SUM(party_size), 0) INTO v_seats_taken
        FROM guests
        WHERE table_id = p_table_id
          AND is_deleted = 0
          AND id <> p_guest_id;

        IF v_seats_taken + p_party_size > v_capacity THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'This table does not have enough seats left for this guest';
        END IF;
    END IF;
END$$

-- The guests triggers that call check_table_capacity are created further
-- down (HALLS section), after guests.hall exists — their bodies also check
-- NEW.hall, and MariaDB rejects a trigger that references a column the
-- table doesn't have yet.

-- =====================================================================
-- VIEWS
-- =====================================================================

CREATE OR REPLACE VIEW v_table_occupancy AS
SELECT
    st.id                                          AS table_id,
    st.table_number,
    st.capacity,
    COALESCE(SUM(g.party_size), 0)                 AS seats_taken,
    st.capacity - COALESCE(SUM(g.party_size), 0)    AS seats_left,
    COUNT(g.id)                                     AS parties_seated
FROM seating_tables st
LEFT JOIN guests g ON g.table_id = st.id AND g.is_deleted = 0
GROUP BY st.id, st.table_number, st.capacity
ORDER BY st.table_number$$

CREATE OR REPLACE VIEW v_guest_media_allowance AS
SELECT
    g.id AS guest_id,
    g.display_name,
    SUM(CASE WHEN gm.media_type = 'photo' THEN 1 ELSE 0 END)      AS photos_used,
    15 - SUM(CASE WHEN gm.media_type = 'photo' THEN 1 ELSE 0 END) AS photos_remaining,
    SUM(CASE WHEN gm.media_type = 'video' THEN 1 ELSE 0 END)      AS videos_used,
    4 - SUM(CASE WHEN gm.media_type = 'video' THEN 1 ELSE 0 END)  AS videos_remaining
FROM guests g
LEFT JOIN guest_media gm ON gm.guest_id = g.id
WHERE g.is_deleted = 0
GROUP BY g.id, g.display_name$$

CREATE OR REPLACE VIEW v_table_seating_super_admin AS
SELECT
    st.table_number,
    st.capacity,
    occ.seats_left,
    g.id           AS guest_id,
    g.display_name,
    g.party_size,
    a.username     AS owning_admin
FROM seating_tables st
JOIN v_table_occupancy occ ON occ.table_id = st.id
LEFT JOIN guests g ON g.table_id = st.id AND g.is_deleted = 0
LEFT JOIN admins a ON a.id = g.admin_id
ORDER BY st.table_number, g.display_name$$

-- ---------------------------------------------------------------------
-- Seating chart scoped to one admin — MariaDB has no table-valued SQL
-- function like Postgres, so this is a stored procedure returning a
-- result set instead of a view: CALL get_seating_chart_for_admin('...').
-- Defined further down (after the side/label columns exist below), not
-- here — the procedure body needs v_table_occupancy's "label" column,
-- which the HALL LAYOUT section below adds.
-- ---------------------------------------------------------------------

-- =====================================================================
-- HALL LAYOUT — bride/groom/head sides for seating_tables, plus which
-- side each admin belongs to. Appended as ALTER statements (not folded
-- into the CREATE TABLE blocks above) so this stays safely re-runnable
-- against a database that already has the original tables — every
-- ALTER here uses IF [NOT] EXISTS, a MariaDB extension supported since
-- 10.1.4/10.0.2, so re-running this on a database that's already been
-- migrated is a clean no-op rather than an error.
-- =====================================================================

-- Which side an admin belongs to. NULL for super_admin (not tied to a
-- side); required for a regular admin — enforced in the application
-- layer at admin-creation time, not by a NOT NULL here, since super_admin
-- genuinely has no side.
ALTER TABLE admins
    ADD COLUMN IF NOT EXISTS side VARCHAR(10) NULL CHECK (side IN ('bride', 'groom'))$$

-- seating_tables gains a side. table_number becomes nullable (the head
-- table isn't numbered) and its uniqueness becomes per-side instead of
-- global (both a "1B" and a "1D" table can coexist).
ALTER TABLE seating_tables
    ADD COLUMN IF NOT EXISTS side VARCHAR(10) NOT NULL DEFAULT 'bride' CHECK (side IN ('bride', 'groom', 'head'))$$

ALTER TABLE seating_tables MODIFY COLUMN table_number INT NULL$$

ALTER TABLE seating_tables DROP INDEX IF EXISTS uk_seating_tables_number$$

-- (side, table_number) was the uniqueness rule before halls existed —
-- superseded by uk_seating_tables_hall_side_number below.
ALTER TABLE seating_tables DROP INDEX IF EXISTS uk_seating_tables_side_number$$

-- =====================================================================
-- HALLS — the wedding is celebrated in two places: the main Tashkent
-- hall (Santini: head/bride/groom tables) and a second, groom-side-only
-- hall in Samarkand (Bogishamol). Every table and every guest belongs to
-- exactly one hall; a guest's hall also decides which invitation (venue,
-- date, time) they see. Existing rows default to 'tashkent'.
-- =====================================================================

ALTER TABLE seating_tables
    ADD COLUMN IF NOT EXISTS hall VARCHAR(20) NOT NULL DEFAULT 'tashkent' CHECK (hall IN ('tashkent', 'samarkand'))$$

-- Table numbers are unique per hall and side, so Samarkand's "1B".."8B"
-- coexist with Tashkent's own "1B", "2B", ...
ALTER TABLE seating_tables ADD UNIQUE INDEX IF NOT EXISTS uk_seating_tables_hall_side_number (hall, side, table_number)$$

-- Samarkand is the groom side's hall only — no bride or head tables there.
-- Guarded via information_schema rather than ADD CONSTRAINT IF NOT EXISTS,
-- which older MariaDB releases (e.g. the 10.x that apt installs) may not accept.
DROP PROCEDURE IF EXISTS add_samarkand_groom_check$$

CREATE PROCEDURE add_samarkand_groom_check()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.TABLE_CONSTRAINTS
                   WHERE CONSTRAINT_SCHEMA = DATABASE()
                     AND TABLE_NAME = 'seating_tables'
                     AND CONSTRAINT_NAME = 'ck_seating_tables_samarkand_groom') THEN
        ALTER TABLE seating_tables
            ADD CONSTRAINT ck_seating_tables_samarkand_groom CHECK (hall <> 'samarkand' OR side = 'groom');
    END IF;
END$$

CALL add_samarkand_groom_check()$$
DROP PROCEDURE IF EXISTS add_samarkand_groom_check$$

ALTER TABLE guests
    ADD COLUMN IF NOT EXISTS hall VARCHAR(20) NOT NULL DEFAULT 'tashkent' CHECK (hall IN ('tashkent', 'samarkand'))$$

-- A "hall admin": a regular admin limited to one hall (e.g. sam_hall,
-- groom side, Samarkand only), who manages every guest their side has in
-- that hall — not just the ones they created. NULL (every other admin)
-- means every hall open to their side, own guests only.
ALTER TABLE admins
    ADD COLUMN IF NOT EXISTS hall VARCHAR(20) NULL CHECK (hall IN ('tashkent', 'samarkand'))$$

-- The original 8 generic tables (from before this feature existed) have
-- no meaningful side and don't fit the new model — clear them out ONCE
-- so data.sql can seed a proper head/bride/groom layout instead.
--
-- This must NOT run on every restart — schema.sql re-runs on every boot,
-- and admins will be creating/deleting their own tables through the app
-- from now on, so an unconditional DELETE here would silently wipe their
-- work on every subsequent restart. Guarded by a small migrations-applied
-- table so the cleanup fires exactly once, ever.

CREATE TABLE IF NOT EXISTS schema_migrations (
    migration_name  VARCHAR(100) NOT NULL PRIMARY KEY,
    applied_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

DROP PROCEDURE IF EXISTS apply_hall_layout_migration$$

CREATE PROCEDURE apply_hall_layout_migration()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE migration_name = 'hall_layout_v1') THEN
        DELETE FROM seating_tables;
        INSERT INTO schema_migrations (migration_name) VALUES ('hall_layout_v1');
    END IF;
END$$

CALL apply_hall_layout_migration()$$
DROP PROCEDURE IF EXISTS apply_hall_layout_migration$$

-- ---------------------------------------------------------------------
-- Views/procedures updated to carry side + a display label
-- ---------------------------------------------------------------------

CREATE OR REPLACE VIEW v_table_occupancy AS
SELECT
    st.id AS table_id,
    st.hall,
    st.side,
    st.table_number,
    CASE
        WHEN st.side = 'head' THEN 'Head Table'
        WHEN st.side = 'bride' THEN CONCAT(st.table_number, 'D')
        WHEN st.side = 'groom' THEN CONCAT(st.table_number, 'B')
    END AS label,
    st.capacity,
    COALESCE(SUM(g.party_size), 0) AS seats_taken,
    st.capacity - COALESCE(SUM(g.party_size), 0) AS seats_left,
    COUNT(g.id) AS parties_seated
FROM seating_tables st
LEFT JOIN guests g ON g.table_id = st.id AND g.is_deleted = 0
GROUP BY st.id, st.hall, st.side, st.table_number, st.capacity
ORDER BY st.hall, st.side, st.table_number$$

DROP PROCEDURE IF EXISTS get_seating_chart_for_admin$$

CREATE PROCEDURE get_seating_chart_for_admin(IN p_admin_id CHAR(36))
BEGIN
    -- super_admin sees every guest by name, same as if every guest were
    -- its own; a hall admin (admins.hall set) likewise sees every guest
    -- its side has in its hall — mirrors AdminPrincipal.canManageGuest.
    -- Looked up once here rather than repeating the subquery per row.
    DECLARE v_is_super_admin BOOLEAN DEFAULT FALSE;
    DECLARE v_side VARCHAR(10) DEFAULT NULL;
    DECLARE v_hall VARCHAR(20) DEFAULT NULL;
    SELECT (role = 'super_admin'), side, hall INTO v_is_super_admin, v_side, v_hall
    FROM admins WHERE id = p_admin_id;

    SELECT
        st.id AS table_id,
        st.hall,
        st.side,
        st.table_number,
        occ.label,
        st.capacity,
        occ.seats_left,
        g.id AS guest_id,
        CASE WHEN v_is_super_admin OR g.admin_id = p_admin_id
                  OR (v_hall IS NOT NULL AND g.hall = v_hall AND ga.side = v_side)
             THEN g.display_name
             ELSE CONCAT('Reserved (', g.party_size, ' seats)')
        END AS display_name,
        CASE WHEN v_is_super_admin OR g.admin_id = p_admin_id
                  OR (v_hall IS NOT NULL AND g.hall = v_hall AND ga.side = v_side)
             THEN g.landing_slug
             ELSE NULL
        END AS landing_slug,
        g.party_size,
        (v_is_super_admin OR g.admin_id = p_admin_id
         OR (v_hall IS NOT NULL AND g.hall = v_hall AND ga.side = v_side)) AS is_own_guest
    FROM seating_tables st
    JOIN v_table_occupancy occ ON occ.table_id = st.id
    LEFT JOIN guests g ON g.table_id = st.id AND g.is_deleted = 0
    LEFT JOIN admins ga ON ga.id = g.admin_id
    ORDER BY st.hall, st.side, st.table_number, is_own_guest DESC, g.display_name;
END$$

-- ---------------------------------------------------------------------
-- Guests triggers: a guest may only sit at a table in their own hall,
-- and the table must have room (check_table_capacity, defined above).
-- ---------------------------------------------------------------------

DROP PROCEDURE IF EXISTS check_table_hall$$

CREATE PROCEDURE check_table_hall(
    IN p_table_id CHAR(36),
    IN p_hall VARCHAR(20)
)
BEGIN
    DECLARE v_table_hall VARCHAR(20);

    IF p_table_id IS NOT NULL THEN
        SELECT hall INTO v_table_hall FROM seating_tables WHERE id = p_table_id;

        IF v_table_hall <> p_hall THEN
            SIGNAL SQLSTATE '45000'
                SET MESSAGE_TEXT = 'This table is in a different hall than the guest is invited to';
        END IF;
    END IF;
END$$

DROP TRIGGER IF EXISTS trg_guests_table_capacity_insert$$
DROP TRIGGER IF EXISTS trg_guests_table_capacity_update$$

CREATE TRIGGER trg_guests_table_capacity_insert
BEFORE INSERT ON guests
FOR EACH ROW
BEGIN
    CALL check_table_hall(NEW.table_id, NEW.hall);
    CALL check_table_capacity(NEW.table_id, NEW.id, NEW.party_size);
END$$

CREATE TRIGGER trg_guests_table_capacity_update
BEFORE UPDATE ON guests
FOR EACH ROW
BEGIN
    CALL check_table_hall(NEW.table_id, NEW.hall);
    CALL check_table_capacity(NEW.table_id, NEW.id, NEW.party_size);
END$$
-- =====================================================================
-- MEDIA PROCESSING — every guest upload is converted server-side into
-- copies every browser can show (see MediaProcessingQueue): photos
-- (including iPhone HEIC) into a metadata-stripped JPEG display copy and
-- a thumbnail, videos (including iPhone HEVC / HDR .mov) into an H.264
-- MP4 and a poster frame. storage_key stays the untouched original.
-- Existing rows default to 'processing' so the startup recovery in
-- MediaProcessingQueue converts anything uploaded before this existed.
-- =====================================================================

ALTER TABLE guest_media ADD COLUMN IF NOT EXISTS display_key VARCHAR(500) NULL$$

ALTER TABLE guest_media ADD COLUMN IF NOT EXISTS thumb_key VARCHAR(500) NULL$$

ALTER TABLE guest_media
    ADD COLUMN IF NOT EXISTS processing_status VARCHAR(12) NOT NULL DEFAULT 'processing'
        CHECK (processing_status IN ('processing', 'ready', 'failed'))$$

ALTER TABLE guest_media ADD COLUMN IF NOT EXISTS processing_error VARCHAR(500) NULL$$

-- The shared photo feed reads every ready photo in a hall.
ALTER TABLE guest_media ADD INDEX IF NOT EXISTS idx_guest_media_type_status (media_type, processing_status)$$

-- Videos are at most 60 seconds (app.media.max-video-seconds) — last line
-- of defense behind GuestMediaService/MediaUploadService, the same way
-- trg_guest_media_limit backs the per-guest counts. NULL is allowed only
-- for rows from before durations were measured. Guarded the same way as
-- ck_seating_tables_samarkand_groom above.
DROP PROCEDURE IF EXISTS add_video_duration_check$$

CREATE PROCEDURE add_video_duration_check()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.TABLE_CONSTRAINTS
                   WHERE CONSTRAINT_SCHEMA = DATABASE()
                     AND TABLE_NAME = 'guest_media'
                     AND CONSTRAINT_NAME = 'ck_guest_media_video_duration') THEN
        ALTER TABLE guest_media
            ADD CONSTRAINT ck_guest_media_video_duration
                CHECK (media_type <> 'video' OR duration_seconds IS NULL OR duration_seconds <= 60);
    END IF;
END$$

CALL add_video_duration_check()$$
DROP PROCEDURE IF EXISTS add_video_duration_check$$

-- ---------------------------------------------------------------------
-- MEDIA UPLOADS — resumable, chunked upload sessions (MediaUploadService).
-- The bytes received so far live in a scratch file next to the media
-- storage; a session row disappears once the upload completes (it becomes
-- a guest_media row), is cancelled, or goes stale.
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS media_uploads (
    id                  CHAR(36) NOT NULL PRIMARY KEY,
    guest_id            CHAR(36) NOT NULL,
    media_type          VARCHAR(10) NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    size_bytes          BIGINT NOT NULL,
    received_bytes      BIGINT NOT NULL DEFAULT 0,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_media_uploads_type CHECK (media_type IN ('photo', 'video')),
    CONSTRAINT ck_media_uploads_size CHECK (size_bytes > 0),
    CONSTRAINT ck_media_uploads_received CHECK (received_bytes >= 0 AND received_bytes <= size_bytes),
    CONSTRAINT fk_media_uploads_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,

    INDEX idx_media_uploads_guest_type (guest_id, media_type),
    INDEX idx_media_uploads_updated_at (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$


-- =====================================================================
-- MEDIA VISIBILITY — the guest picks, per upload, whether a photo or
-- video is shared with every guest in their hall ('public', the feed) or
-- kept to themselves ('private'). Admins see both either way (see
-- GuestMediaService). Before this existed photos were always shared and
-- videos always private, so existing rows are backfilled that way — once,
-- when the column is added, so a re-run never overrides a guest's choice.
-- =====================================================================

DROP PROCEDURE IF EXISTS add_media_visibility$$

CREATE PROCEDURE add_media_visibility()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.COLUMNS
                   WHERE TABLE_SCHEMA = DATABASE()
                     AND TABLE_NAME = 'guest_media'
                     AND COLUMN_NAME = 'visibility') THEN
        ALTER TABLE guest_media
            ADD COLUMN visibility VARCHAR(10) NOT NULL DEFAULT 'public'
                CHECK (visibility IN ('public', 'private'));
        UPDATE guest_media SET visibility = 'private' WHERE media_type = 'video';
    END IF;
END$$

CALL add_media_visibility()$$
DROP PROCEDURE IF EXISTS add_media_visibility$$

-- Chosen when the upload starts, carried over to guest_media on completion.
-- A session from before this existed defaults to the safe side.
ALTER TABLE media_uploads
    ADD COLUMN IF NOT EXISTS visibility VARCHAR(10) NOT NULL DEFAULT 'private'
        CHECK (visibility IN ('public', 'private'))$$


-- =====================================================================
-- QUESTS — photo and video challenges for the guests of one hall ("Selfie
-- with the groom", "The cake before it's cut"). Hall-wide content, managed
-- by any admin who can open that hall (QuestService), like the hall
-- itself. A guest completes a quest by uploading what it asks for
-- (media_type) through the normal media pipeline: the upload session and
-- the resulting guest_media row carry quest_id. One upload per quest per
-- guest; deleting it (or a banker rejecting it, see BANK below) re-opens
-- the quest, deleting the quest keeps the uploads as plain ones.
-- =====================================================================

CREATE TABLE IF NOT EXISTS quests (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    hall            VARCHAR(20) NOT NULL,
    title           VARCHAR(150) NOT NULL,
    description     VARCHAR(600) NULL,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_quests_hall CHECK (hall IN ('tashkent', 'samarkand')),
    INDEX idx_quests_hall (hall, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- What completes the quest: a photo, or a video ("10 seconds of the best
-- dancer"). Added after the table first shipped, hence the ALTER.
ALTER TABLE quests
    ADD COLUMN IF NOT EXISTS media_type VARCHAR(10) NOT NULL DEFAULT 'photo' CHECK (media_type IN ('photo', 'video'))$$

ALTER TABLE guest_media ADD COLUMN IF NOT EXISTS quest_id CHAR(36) NULL$$

ALTER TABLE media_uploads ADD COLUMN IF NOT EXISTS quest_id CHAR(36) NULL$$

-- NULLs don't collide in a UNIQUE key, so plain photos are unaffected.
ALTER TABLE guest_media ADD UNIQUE INDEX IF NOT EXISTS uk_guest_media_quest (guest_id, quest_id)$$

DROP PROCEDURE IF EXISTS add_quest_foreign_keys$$

CREATE PROCEDURE add_quest_foreign_keys()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.TABLE_CONSTRAINTS
                   WHERE CONSTRAINT_SCHEMA = DATABASE()
                     AND TABLE_NAME = 'guest_media'
                     AND CONSTRAINT_NAME = 'fk_guest_media_quest') THEN
        ALTER TABLE guest_media
            ADD CONSTRAINT fk_guest_media_quest FOREIGN KEY (quest_id) REFERENCES quests (id) ON DELETE SET NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.TABLE_CONSTRAINTS
                   WHERE CONSTRAINT_SCHEMA = DATABASE()
                     AND TABLE_NAME = 'media_uploads'
                     AND CONSTRAINT_NAME = 'fk_media_uploads_quest') THEN
        ALTER TABLE media_uploads
            ADD CONSTRAINT fk_media_uploads_quest FOREIGN KEY (quest_id) REFERENCES quests (id) ON DELETE SET NULL;
    END IF;
END$$

CALL add_quest_foreign_keys()$$
DROP PROCEDURE IF EXISTS add_quest_foreign_keys$$

-- A quest upload must be what the quest asks for (photo or video), of a
-- quest in the guest's own hall — last line of defense behind
-- MediaUploadService.start / QuestService.requireOpenQuest.
DROP PROCEDURE IF EXISTS check_media_quest$$

CREATE PROCEDURE check_media_quest(
    IN p_quest_id CHAR(36),
    IN p_guest_id CHAR(36),
    IN p_media_type VARCHAR(10)
)
BEGIN
    DECLARE v_quest_hall VARCHAR(20);
    DECLARE v_quest_media_type VARCHAR(10);
    DECLARE v_guest_hall VARCHAR(20);

    IF p_quest_id IS NOT NULL THEN
        SELECT hall, media_type INTO v_quest_hall, v_quest_media_type FROM quests WHERE id = p_quest_id;
        IF p_media_type <> v_quest_media_type THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This quest asks for a different kind of upload (photo or video)';
        END IF;
        SELECT hall INTO v_guest_hall FROM guests WHERE id = p_guest_id;
        IF v_quest_hall <> v_guest_hall THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This quest is for a different hall than the guest is invited to';
        END IF;
    END IF;
END$$

DROP TRIGGER IF EXISTS trg_guest_media_quest_insert$$
DROP TRIGGER IF EXISTS trg_guest_media_quest_update$$

CREATE TRIGGER trg_guest_media_quest_insert
BEFORE INSERT ON guest_media
FOR EACH ROW
BEGIN
    CALL check_media_quest(NEW.quest_id, NEW.guest_id, NEW.media_type);
END$$

-- ON DELETE SET NULL of fk_guest_media_quest doesn't fire triggers, and a
-- NULL quest passes the check anyway.
CREATE TRIGGER trg_guest_media_quest_update
BEFORE UPDATE ON guest_media
FOR EACH ROW
BEGIN
    IF NOT (NEW.quest_id <=> OLD.quest_id) THEN
        CALL check_media_quest(NEW.quest_id, NEW.guest_id, NEW.media_type);
    END IF;
END$$


-- =====================================================================
-- BETS — "who cries first?"-style predictions for the guests of one hall,
-- no money involved. An admin opens a bet with its options; guests pick
-- one (and may change it) while it's 'open'; 'closed' stops picks; once
-- the admin marks the right option it's 'settled' and counts for the
-- hall's leaderboard (BetService). Like quests, hall-wide content managed
-- by any admin who can open the hall.
-- =====================================================================

CREATE TABLE IF NOT EXISTS bets (
    id                  CHAR(36) NOT NULL PRIMARY KEY,
    hall                VARCHAR(20) NOT NULL,
    question            VARCHAR(300) NOT NULL,
    status              VARCHAR(10) NOT NULL DEFAULT 'open',
    correct_option_id   CHAR(36) NULL,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_bets_hall CHECK (hall IN ('tashkent', 'samarkand')),
    CONSTRAINT ck_bets_status CHECK (status IN ('open', 'closed', 'settled')),
    -- Settled exactly when the right answer is known.
    CONSTRAINT ck_bets_settled CHECK ((status = 'settled') = (correct_option_id IS NOT NULL)),
    INDEX idx_bets_hall (hall, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

CREATE TABLE IF NOT EXISTS bet_options (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    bet_id          CHAR(36) NOT NULL,
    label           VARCHAR(150) NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,

    -- Target of bet_votes' composite FK: a vote's option belongs to its bet.
    CONSTRAINT uk_bet_options_bet_option UNIQUE (bet_id, id),
    CONSTRAINT fk_bet_options_bet FOREIGN KEY (bet_id) REFERENCES bets (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

CREATE TABLE IF NOT EXISTS bet_votes (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    bet_id          CHAR(36) NOT NULL,
    option_id       CHAR(36) NOT NULL,
    guest_id        CHAR(36) NOT NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT uk_bet_votes_bet_guest UNIQUE (bet_id, guest_id),
    CONSTRAINT fk_bet_votes_option FOREIGN KEY (bet_id, option_id) REFERENCES bet_options (bet_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_bet_votes_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,
    INDEX idx_bet_votes_guest (guest_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- correct_option_id has no FK (bets <-> bet_options would be a cycle that
-- blocks cascading deletes); this trigger keeps it pointing at one of the
-- bet's own options instead.
DROP TRIGGER IF EXISTS trg_bets_correct_option$$

CREATE TRIGGER trg_bets_correct_option
BEFORE UPDATE ON bets
FOR EACH ROW
BEGIN
    IF NEW.correct_option_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM bet_options WHERE id = NEW.correct_option_id AND bet_id = NEW.id) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'The right answer must be one of the options of this bet';
    END IF;
END$$

-- Picks only while the bet is open, and only by guests of the bet's hall.
DROP PROCEDURE IF EXISTS check_bet_vote$$

CREATE PROCEDURE check_bet_vote(
    IN p_bet_id CHAR(36),
    IN p_guest_id CHAR(36)
)
BEGIN
    DECLARE v_status VARCHAR(10);
    DECLARE v_bet_hall VARCHAR(20);
    DECLARE v_guest_hall VARCHAR(20);

    SELECT status, hall INTO v_status, v_bet_hall FROM bets WHERE id = p_bet_id;
    SELECT hall INTO v_guest_hall FROM guests WHERE id = p_guest_id;

    IF v_status <> 'open' THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This bet is no longer taking picks';
    END IF;
    IF v_bet_hall <> v_guest_hall THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This bet is for a different hall than the guest is invited to';
    END IF;
END$$

DROP TRIGGER IF EXISTS trg_bet_votes_insert$$
DROP TRIGGER IF EXISTS trg_bet_votes_update$$

CREATE TRIGGER trg_bet_votes_insert
BEFORE INSERT ON bet_votes
FOR EACH ROW
BEGIN
    CALL check_bet_vote(NEW.bet_id, NEW.guest_id);
END$$

CREATE TRIGGER trg_bet_votes_update
BEFORE UPDATE ON bet_votes
FOR EACH ROW
BEGIN
    CALL check_bet_vote(NEW.bet_id, NEW.guest_id);
END$$


-- =====================================================================
-- PLAYLIST — the band's songs per hall, liked and bought by the guests
-- (PlaylistService). Hall-wide content like quests and bets: any admin
-- who can open the hall manages it, and so does that hall's DJ (a 'dj'
-- account — see below).
--
--   * Likes: one per guest and song, open until playlist_settings.
--     likes_close_at (20:50 on the evening). The two most-liked songs at
--     that moment are played after it; likes freeze so the result can't
--     move any more.
--   * Orders: a guest buys a song for ducats — paper props handed out at
--     the wedding, so no balance lives here. The order waits as 'pending'
--     until the guest pays the DJ in person, who marks it 'paid' (it's
--     now in the band's queue) and then 'played'; 'cancelled' if it never
--     happens.
--
-- Times in playlist_settings are the venue's wall clock: Uzbekistan is
-- UTC+5 all year (no DST), so the triggers compare against UTC+5 directly
-- — independent of the server's or the JVM's own time zone. Mirrored by
-- PlaylistService.VENUE_OFFSET.
-- =====================================================================

-- A DJ: a login limited to one hall's playlist (SecurityConfig lets the
-- 'dj' role reach /api/playlist/** only). No side, but always a hall.
DROP PROCEDURE IF EXISTS apply_admins_dj_role_migration$$

CREATE PROCEDURE apply_admins_dj_role_migration()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE migration_name = 'admins_dj_role_v1') THEN
        ALTER TABLE admins DROP CONSTRAINT IF EXISTS ck_admins_role;
        ALTER TABLE admins ADD CONSTRAINT ck_admins_role CHECK (role IN ('super_admin', 'admin', 'dj'));
        ALTER TABLE admins ADD CONSTRAINT ck_admins_dj_hall CHECK (role <> 'dj' OR (hall IS NOT NULL AND side IS NULL));
        INSERT INTO schema_migrations (migration_name) VALUES ('admins_dj_role_v1');
    END IF;
END$$

CALL apply_admins_dj_role_migration()$$
DROP PROCEDURE IF EXISTS apply_admins_dj_role_migration$$

CREATE TABLE IF NOT EXISTS playlist_settings (
    hall            VARCHAR(20) NOT NULL PRIMARY KEY,
    -- Venue wall-clock time (UTC+5) at which likes freeze.
    likes_close_at  DATETIME NOT NULL,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_playlist_settings_hall CHECK (hall IN ('tashkent', 'samarkand'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

CREATE TABLE IF NOT EXISTS songs (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    hall            VARCHAR(20) NOT NULL,
    artist          VARCHAR(150) NOT NULL,
    title           VARCHAR(200) NOT NULL,
    language        VARCHAR(10) NOT NULL,
    -- Hidden songs stay out of the guests' list but keep their likes and orders.
    is_active       TINYINT(1) NOT NULL DEFAULT 1,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_songs_hall CHECK (hall IN ('tashkent', 'samarkand')),
    CONSTRAINT ck_songs_language CHECK (language IN ('en', 'ru', 'uz', 'tr', 'de', 'fr', 'other')),
    CONSTRAINT uk_songs_hall_artist_title UNIQUE (hall, artist, title),
    INDEX idx_songs_hall (hall, language)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

CREATE TABLE IF NOT EXISTS song_likes (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    song_id         CHAR(36) NOT NULL,
    guest_id        CHAR(36) NOT NULL,
    created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    CONSTRAINT uk_song_likes_song_guest UNIQUE (song_id, guest_id),
    CONSTRAINT fk_song_likes_song FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE,
    CONSTRAINT fk_song_likes_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,
    INDEX idx_song_likes_guest (guest_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

CREATE TABLE IF NOT EXISTS song_orders (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    song_id         CHAR(36) NOT NULL,
    guest_id        CHAR(36) NOT NULL,
    status          VARCHAR(10) NOT NULL DEFAULT 'pending',
    -- In ducats, as it was when ordered (app.playlist.song-price).
    price           INT NOT NULL,
    paid_at         DATETIME NULL,
    played_at       DATETIME NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT ck_song_orders_status CHECK (status IN ('pending', 'paid', 'played', 'cancelled')),
    CONSTRAINT ck_song_orders_price CHECK (price > 0),
    CONSTRAINT fk_song_orders_song FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE,
    CONSTRAINT fk_song_orders_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,
    INDEX idx_song_orders_guest (guest_id, status),
    INDEX idx_song_orders_song (song_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- Likes (and taking a like back) only for a visible song of the guest's
-- own hall, and only until the hall's likes_close_at — after that the
-- top two are final. Deletes cascading from songs/guests don't fire
-- triggers, so removing a song after the freeze still works.
DROP PROCEDURE IF EXISTS check_song_like$$

CREATE PROCEDURE check_song_like(
    IN p_song_id CHAR(36),
    IN p_guest_id CHAR(36),
    IN p_is_insert TINYINT
)
BEGIN
    DECLARE v_song_hall VARCHAR(20);
    DECLARE v_song_active TINYINT;
    DECLARE v_guest_hall VARCHAR(20);
    DECLARE v_close_at DATETIME;

    SELECT hall, is_active INTO v_song_hall, v_song_active FROM songs WHERE id = p_song_id;
    SELECT hall INTO v_guest_hall FROM guests WHERE id = p_guest_id;
    SELECT likes_close_at INTO v_close_at FROM playlist_settings WHERE hall = v_song_hall;

    IF p_is_insert = 1 AND v_song_hall <> v_guest_hall THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This song is for a different hall than the guest is invited to';
    END IF;
    IF p_is_insert = 1 AND v_song_active = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This song is not on the playlist';
    END IF;
    IF v_close_at IS NOT NULL AND UTC_TIMESTAMP() + INTERVAL 5 HOUR >= v_close_at THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Likes are closed for tonight';
    END IF;
END$$

DROP TRIGGER IF EXISTS trg_song_likes_insert$$
DROP TRIGGER IF EXISTS trg_song_likes_delete$$

CREATE TRIGGER trg_song_likes_insert
BEFORE INSERT ON song_likes
FOR EACH ROW
BEGIN
    CALL check_song_like(NEW.song_id, NEW.guest_id, 1);
END$$

CREATE TRIGGER trg_song_likes_delete
BEFORE DELETE ON song_likes
FOR EACH ROW
BEGIN
    CALL check_song_like(OLD.song_id, OLD.guest_id, 0);
END$$

-- An order is for a visible song of the guest's own hall, and a guest has
-- at most 3 orders waiting for payment at a time (app.playlist.
-- max-pending-orders — change together).
DROP TRIGGER IF EXISTS trg_song_orders_insert$$

CREATE TRIGGER trg_song_orders_insert
BEFORE INSERT ON song_orders
FOR EACH ROW
BEGIN
    DECLARE v_song_hall VARCHAR(20);
    DECLARE v_song_active TINYINT;
    DECLARE v_guest_hall VARCHAR(20);

    SELECT hall, is_active INTO v_song_hall, v_song_active FROM songs WHERE id = NEW.song_id;
    SELECT hall INTO v_guest_hall FROM guests WHERE id = NEW.guest_id;

    IF v_song_hall <> v_guest_hall THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This song is for a different hall than the guest is invited to';
    END IF;
    IF v_song_active = 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This song is not on the playlist';
    END IF;
    IF NEW.status = 'pending'
       AND (SELECT COUNT(*) FROM song_orders WHERE guest_id = NEW.guest_id AND status = 'pending') >= 3 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Too many orders waiting for payment';
    END IF;
END$$


-- =====================================================================
-- BANK — quests pay out ducats (the wedding's paper money, also what the
-- DJ takes for a song). Each quest is worth `reward` ducats; a guest's
-- quest is Open (no upload), Done (an upload that didn't fail conversion)
-- or Paid (a quest_payouts row). Guests collect at the bank table: a
-- banker scans the QR code on the guest's quests page, or types their
-- own 4-digit PIN on the guest's phone, looks at each Done quest's photo
-- or video and accepts or rejects it (BankService). Accepted ones become
-- Paid and the banker hands over the coins; a rejected upload is
-- detached from its quest (kept as a plain upload) and noted in
-- quest_rejections, so the quest is Open again for a retry. A payout row
-- is never removed by the guest (retaking the photo doesn't re-open it),
-- so no quest pays twice.
-- =====================================================================

ALTER TABLE quests
    ADD COLUMN IF NOT EXISTS reward INT NOT NULL DEFAULT 5 CHECK (reward BETWEEN 1 AND 1000)$$

-- A banker: like a DJ, a login limited to one hall (SecurityConfig lets
-- the 'banker' role reach /api/bank/** only). No side, but always a hall.
DROP PROCEDURE IF EXISTS apply_admins_banker_role_migration$$

CREATE PROCEDURE apply_admins_banker_role_migration()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE migration_name = 'admins_banker_role_v1') THEN
        ALTER TABLE admins DROP CONSTRAINT IF EXISTS ck_admins_role;
        ALTER TABLE admins ADD CONSTRAINT ck_admins_role CHECK (role IN ('super_admin', 'admin', 'dj', 'banker'));
        ALTER TABLE admins ADD CONSTRAINT ck_admins_banker_hall CHECK (role <> 'banker' OR (hall IS NOT NULL AND side IS NULL));
        INSERT INTO schema_migrations (migration_name) VALUES ('admins_banker_role_v1');
    END IF;
END$$

CALL apply_admins_banker_role_migration()$$
DROP PROCEDURE IF EXISTS apply_admins_banker_role_migration$$

-- The PIN a banker (or an admin working the bank table) types on a
-- guest's phone, as an HMAC keyed off the server secret (BankCodes) —
-- never the digits themselves. Unique, so a PIN names one person.
ALTER TABLE admins ADD COLUMN IF NOT EXISTS bank_pin CHAR(64) NULL$$

ALTER TABLE admins ADD UNIQUE INDEX IF NOT EXISTS uk_admins_bank_pin (bank_pin)$$

CREATE TABLE IF NOT EXISTS quest_payouts (
    id              CHAR(36) NOT NULL PRIMARY KEY,
    -- NULL once the quest is deleted; quest_title keeps what it was.
    quest_id        CHAR(36) NULL,
    quest_title     VARCHAR(150) NOT NULL,
    guest_id        CHAR(36) NOT NULL,
    -- Ducats handed over, as the quest's reward was at the time.
    coins           INT NOT NULL,
    paid_by         CHAR(36) NULL,
    method          VARCHAR(10) NOT NULL,
    -- Shared by the quests paid in one go (one visit to the bank table).
    batch_id        CHAR(36) NOT NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_quest_payouts_guest_quest UNIQUE (guest_id, quest_id),
    CONSTRAINT ck_quest_payouts_coins CHECK (coins > 0),
    CONSTRAINT ck_quest_payouts_method CHECK (method IN ('qr', 'pin')),
    CONSTRAINT fk_quest_payouts_quest FOREIGN KEY (quest_id) REFERENCES quests (id) ON DELETE SET NULL,
    CONSTRAINT fk_quest_payouts_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,
    CONSTRAINT fk_quest_payouts_paid_by FOREIGN KEY (paid_by) REFERENCES admins (id) ON DELETE SET NULL,
    INDEX idx_quest_payouts_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- Only a Done quest pays: one of the guest's own hall, with an upload of
-- the guest's for it that didn't fail conversion — last line of defense
-- behind BankService.
DROP TRIGGER IF EXISTS trg_quest_payouts_insert$$

CREATE TRIGGER trg_quest_payouts_insert
BEFORE INSERT ON quest_payouts
FOR EACH ROW
BEGIN
    DECLARE v_quest_hall VARCHAR(20);
    DECLARE v_guest_hall VARCHAR(20);

    SELECT hall INTO v_quest_hall FROM quests WHERE id = NEW.quest_id;
    SELECT hall INTO v_guest_hall FROM guests WHERE id = NEW.guest_id;

    IF v_quest_hall IS NULL OR v_quest_hall <> v_guest_hall THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This quest is for a different hall than the guest is invited to';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM guest_media
                   WHERE guest_id = NEW.guest_id AND quest_id = NEW.quest_id AND processing_status <> 'failed') THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'This quest is not done yet';
    END IF;
END$$

-- The last time a banker rejected a guest's upload for a quest, so the
-- quests page can say why it's open again. Informational only: nothing
-- is blocked by it, and a new upload simply makes the quest Done again.
CREATE TABLE IF NOT EXISTS quest_rejections (
    guest_id        CHAR(36) NOT NULL,
    quest_id        CHAR(36) NOT NULL,
    rejected_by     CHAR(36) NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (guest_id, quest_id),
    CONSTRAINT fk_quest_rejections_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,
    CONSTRAINT fk_quest_rejections_quest FOREIGN KEY (quest_id) REFERENCES quests (id) ON DELETE CASCADE,
    CONSTRAINT fk_quest_rejections_by FOREIGN KEY (rejected_by) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$

-- Wrong PINs typed on a guest's phone: after 5 in a row the PIN path is
-- locked for that guest for 10 minutes (the QR code still works).
CREATE TABLE IF NOT EXISTS bank_pin_attempts (
    guest_id        CHAR(36) NOT NULL PRIMARY KEY,
    failures        INT NOT NULL DEFAULT 0,
    -- UTC, compared against UTC_TIMESTAMP().
    locked_until    DATETIME NULL,

    CONSTRAINT fk_bank_pin_attempts_guest FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci$$
